manifest = "097ea30aded9399a3eebacf3df602fbef0e231b35c29c8dc1bf63c634302881e"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.62.0" ]
revision = "1da34e01ccb41c98b1896b120892fde491630358"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.62.0" ]
revision = "8e0bd7d950d98d4dd62a61b31ad6cd90e0ab3fd9"
