manifest = "8856a0f5514aca0ea482ef14d72e3ad277dce59577f2c43203a6551de2b32c1a"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.59.0" ]
revision = "fe97653ead53ba7826ababa397a054a83020aefb"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.59.0" ]
revision = "ec90e8c6b2f388644b586d11eb1a3543028fa1f5"
