manifest = "69e05e5f09732c739bcb78ab44dd7063d85809d221a5f77a6841240a64906efd"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.66.0" ]
revision = "28f68af48b94b6e0d287dde32e77bb3791517703"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.66.0" ]
revision = "bbc1bc3ec06d91bea9ee8e8e9b900de37998e063"
